#!/bin/bash
cd /root/terraform/cache-services
terraform output elasticache_sg > /root/terraform/tgw/sgid.txt

cd /root/terraform/tgw

cat << EOF > /root/terraform/tgw/sg.txt
security_group_id =
EOF
paste sg.txt sgid.txt >> security_input.tfvars

terraform init

pubkey=$(cat ~/.ssh/id_rsa.pub)
cat << EOF > /root/terraform/tgw/terraform.tfvars
ssh_public_key="${pubkey}"
EOF

set-workdir /root/terraform/tgw

exit 0
